First attempt to add a dispose method for platform objects on iOS, to try to detect hot reload on that platform.
This now has a runtime issue which appears to relate to the fact that the static int variable I've created keeps resetting to zero. This may or not be a Dart or Flutter issue.

I'm seeing this when I load the app, before pressing any buttons:

Xcode build done.                                           59.4s
AblyTestFlutterOldskoolPlugin.m:56 registrar: FlutterEngineRegistrar
AblyTestFlutterOldskoolPlugin.m:85 id = 1
flutter: initPlatformState()
flutter: Creating Ably # 1
flutter: widget build
flutter: Disposing of superceeded Ably Flutter Plugin instance # 1 [Instance of 'AblyImplementation'] (current is now 0)
[VERBOSE-2:dart_isolate.cc(915)] Unhandled exception:
ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
#0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
#1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
#2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
#3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
#4      AblyImplementation._dispose (package:ably_test_flutter_oldskool_plu<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Bad state: Ably Flutter Plugin instance has been superceeded and is no longer current.
#0      AblyImplementation.platformVersion (package:ably_test_flutter_oldskool_plugin/src/ably_implementation.dart:45:117)
#1      _MyAppState.initPlatformState (package:ably_test_flutter_oldskool_plugin_example/main.dart:48:42)
#2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#3      _MyAppState.initPlatformState (package:ably_test_flutter_oldskool_plugin_example/main.dart:38:33)
#4      _MyAppState.initState (package:ably_test_flutter_oldskool_plugin_example/main.dart:34:5)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#9      RenderObjectToWidgetE<…>

And then this when I provision (with success) and then try to create a realtime:

flutter: Error creating Ably Realtime: NoSuchMethodError: The method 'createRealtime' was called on null.
Receiver: null
Tried calling: createRealtime(Instance of 'ClientOptions')